config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'users#my_portfolio'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    begin
      new(
        ticker: ticker_symbol,
        name: client.company(ticker_symbol).company_name,
        last_price: client.price(ticker_symbol)
      )
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    nil
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    redirect_to my_friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Stopped following"
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_list.html.haml
.row
  .col-9
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th{:scope => "col"} Email
          %th{:scope => "col"} First Name
          %th{:scope => "col"} Last Name
          %th{:scope => "col"} Actions
      %tbody
        - @friends.each do |friend|
          %tr
            %td= friend.email
            %td= friend.first_name
            %td= friend.last_name
            %td
              = link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success'
              = link_to 'Stop following', friendship_path(friend), method: :delete, class: 'btn btn-sm btn-warning', data: { confirm: 'Are you sure?' }

app/views/layouts/_messages.html.haml
- if notice
  .alert.alert-success
    = button_tag type: 'button', class: 'close', 'aria-label': 'Close', data: { dismiss: 'alert' } do
      %span{ 'aria-hidden': 'true' } ×
    = notice
- if alert
  .alert.alert-danger
    = button_tag type: 'button', class: 'close', 'aria-label': 'Close', data: { dismiss: 'alert' } do
      %span{ 'aria-hidden': 'true' } ×
    = alert

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to 'Finance Tracker', root_path, class: 'navbar-brand'
    - if current_user
      = button_tag type: 'button', class: 'navbar-toggler', 'aria-controls': 'navbarSupportedContent', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation', data: { target: '#navbarSupportedContent', toggle: 'collapse' } do
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item{ class: request.path == my_portfolio_path ? ' active' : '' }
            = link_to 'My Portfolio', my_portfolio_path, class: 'nav-link'
          %li.nav-item{ class: request.path == my_friends_path ? ' active' : '' }
            = link_to 'My Friends', my_friends_path, class: 'nav-link'
          %li.nav-item.dropdown
            = link_to '#', class: 'nav-link dropdown-toggle', id: 'navbarDropdown', role: 'button', 'aria-expanded': 'false', 'aria-haspopup': 'true', data: { toggle: 'dropdown' } do
              = fa_icon 'user'
              = current_user.full_name.present? ? current_user.full_name : 'Profile'
            .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
              = link_to edit_user_registration_path, class: 'dropdown-item' do
                = fa_icon 'edit'
                Edit profile
              = link_to 'Logout', destroy_user_session_path, class: 'dropdown-item', method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title Finance Tracker
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    .container.pt-4
      = render 'layouts/messages'
      = yield

app/views/stocks/_list.html.haml
.row
  .col-9
    %table.table.table-bordered.table-hover
      %thead
        %tr
          %th{scope: 'col' } Ticker
          %th{scope: 'col' } Name
          %th{scope: 'col' } Price
          %th{scope: 'col' } Actions
      %tbody
        - @tracked_stocks.each do |stock|
          %tr
            %th{ scope: 'row' }= stock.ticker
            %td= stock.name
            %td= stock.last_price
            %td
              - if current_user.can_track_stock?(stock.ticker)
                = link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-sm btn-success", method: :post
              - elsif current_user.id != @user.id
                %span.badge.badge-secondary
                  You are already tracking
                  - if !current_user.under_stock_limit?
                    10 stocks
                  - if current_user.stock_already_tracked?(stock.ticker)
                    this stock
              - if current_user.id == @user.id
                = link_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning'

app/views/users/_friend_result.html.haml
.mb-4
  = render 'layouts/messages'

- if @friends
  .card.card-header.mb-4.col-9
    %table
      %tbody
        - @friends.each do |friend|
          %tr
            %td
              %strong Name:
              = friend.full_name
            %td
              %strong Email:
              = friend.email
            %td
              %strong Actions:
              = link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success'
              - if current_user.not_friends_with?(friend.id)
                = link_to 'Follow friend?', friendships_path(friend: friend), class: 'btn btn-sm btn-success', method: :post
              - else
                %span.badge.badge-secondary You are friends

app/views/users/_friend_result.js.haml
document.querySelector('#friend-results').innerHTML = '#{j render 'users/friend_result.html'}'

app/views/users/_result.html.haml
.mb-4
  = render 'layouts/messages'

- if @stock
  .card.card-header.mb-4.col-9
    %table
      %tbody
        %tr
          %td
            %strong Symbol:
            = @stock.ticker
          %td
            %strong Name:
            = @stock.name
          %td
            - if current_user.can_track_stock?(@stock.ticker)
              = link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: 'btn btn-sm btn-success', method: :post
            - else
              %span.badge.badge-secondary
                You are already tracking
                - if !current_user.under_stock_limit?
                  10 stocks
                - if current_user.stock_already_tracked?(@stock.ticker)
                  this stock

app/views/users/_result.js.haml
document.querySelector('#results').innerHTML = '#{j render 'users/result.html'}'

app/views/users/my_friends.html.haml
%h1 Friends
.search-area
  %h3 Search Friends
  = form_tag search_friend_path, remote: true, method: :get do
    .form-group.row
      .col-sm-9.no-right-padding
        = text_field_tag :friend, params[:friend], placeholder: 'Name or email', autofocus: true, class: 'form-control form-control-lg'
      .col-sm-3.no-left-padding
        = button_tag type: 'submit', class: 'btn btn-success' do
          = fa_icon 'search 2x'

#friend-results
- if !@friends.empty?
  = render 'friends/list'

app/views/users/my_portfolio.html.haml
%h1 My Portfolio
.search-area
  %h3 Search Stocks
  = form_tag search_stock_path, remote: true, method: :get do
    .form-group.row
      .col-sm-9.no-right-padding
        = text_field_tag :stock, params[:stock], placeholder: 'Stock ticker symbol', autofocus: true, class: 'form-control form-control-lg'
      .col-sm-3.no-left-padding
        = button_tag type: 'submit', class: 'btn btn-success' do
          = fa_icon 'search 2x'

#results
- if !@tracked_stocks.empty?
  = render 'stocks/list'

app/views/users/show.html.haml
%h2 User Details
.card.card-header.mb-4
  %table.col-md-12
    %tbody
      %tr
        %td
          %strong Name:
          = @user.full_name
        %td
          %strong Email:
          = @user.email
        %td
          - if current_user.not_friends_with?(@user.id)
            = link_to 'Follow friend?', friendships_path(friend: @user), class: 'btn btn-sm btn-success', method: :post
          - else
            %span.badge.badge-secondary You are friends

- if !@tracked_stocks.empty?
  = render 'stocks/list'
- else
  %p.lead This user is not tracking any stocks

= link_to 'Back', my_friends_path, class: 'btn btn-primary'

app/views/welcome/index.html.haml
%h1 Welcome to the Finance Tracker app
%p Create a welcome page